--- 
title: "New York City Gun Violence Pattern Exploration"
author: "Sai Thrinath Gunda, Tarun Devireddy, Mitali Bante"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

Gun violence has been on the rise in the recent years and has become a serious concern for most people, especially in big cities. There is increasing awareness being developed on the rights and to maintain caution related to gun laws. Considering this, we wanted to explore how the changes in gun laws and awareness has changed the pattern in the occurrence of gun related crime in New York City.

Questions to Explore:

1. Which places in the New York City neighbourhood are the safest from gun violence? On the other end of the spectrum, what are the riskiest neighbourhoods? Is there any association between safety of a neighbourhood and the average income of the neighborhood?

2. Is there a crime trend in terms of an hour of the day/day of the week/month of the year/season or other parameters where the number of violent crimes spike? 

3. Studying the demographics of victims and perpetrators. 
    a. Which age-group/race/gender of victims are at more-risk?
    b. Which age-group/race/gender of perpetrators pose more-risk?
    c. Is there a correlation between the age-group/gender/race of victims and perpetrators?


